import type { Metadata } from "next";
import { instrumentSans, dmSerifDisplay } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${instrumentSans.variable} ${dmSerifDisplay.variable} h-full scroll-smooth antialiased`}
    >
      <body className={`${instrumentSans.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
